bundler_args: ""
language: ruby
gemfile:
  - spec/gemfiles/rails-5.0.gemfile
  - spec/gemfiles/rails-5.1.gemfile
  - spec/gemfiles/rails-5.2.gemfile
  - spec/gemfiles/rails-6.0.gemfile
rvm:
  - "2.4"
  - "2.5"
  - "2.6"

matrix:
  exclude:
    - rvm: "2.4"
      gemfile: spec/gemfiles/rails-6.0.gemfile

script: bundle exec rake spec

before_install:
  - gem update bundler
